Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/BlockLength:
  Max: 40
